print("Hej")
print("jak masz na imie?")
name = input()
print("Witaj", name, ","jak sie masz?")
print("Ile masz lat?")
age = input()
print("Znasz peron Harrego Pottera?")
platform = input()
print("Czy jest sens majac lat", age, "jechac z peronu", platform, "do Hogwartu?")
